// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using IndiaEvents.Models.Models.SqlSampleCheckModel;
using IndiaEventsWebApi.Models.MasterSheets;
using Microsoft.EntityFrameworkCore;
using static IndiaEvents.Models.Models.SqlSampleCheckModel.EventRequestWeb;


namespace IndiaEventsWebApi
{
    public partial class DataContext : DbContext
    {
        public DataContext()
        {
        }

        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }
        public DbSet<HcpMasterData> HCPMaster { get; set; }
        public DbSet<EventRequestWeb> EventRequestsWeb {  get; set; }

    }
}